package com.legendandroidgame.game.BibleBooks;

import com.badlogic.gdx.scenes.scene2d.Stage;

/**
 * Created by Patrick on 8/12/2017.
 */
public class DeuteronomyStack {

    private Stage stage;
    private float time;
    private float minute = 60;
    private BookOfDeuteronomy bookOfDeuteronomy;

    public DeuteronomyStack() {
        stage = new Stage();
        bookOfDeuteronomy = new BookOfDeuteronomy();
    }

    public void deuSwitch(int chapter, int verse){
        switch (chapter){
            case 1: bookOfDeuteronomy.removeAll();
            stage.addActor(bookOfDeuteronomy.getTable1());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 20;
                        break;
                    case 3: time = (0 * minute) + 26;
                        break;
                    case 4: time = (0 * minute) + 38;
                        break;
                    case 5: time = (0 * minute) + 51;
                        break;
                    case 6: time = (0 * minute) + 57;
                        break;
                    case 7: time = (1 * minute) + 2;
                        break;
                    case 8: time = (1 * minute) + 20;
                        break;
                    case 9: time = (1 * minute) + 33;
                        break;
                    case 10: time = (1 * minute) + 38;
                        break;
                    case 11: time = (1 * minute) + 46;
                        break;
                    case 12: time = (1 * minute) + 54;
                        break;
                    case 13: time = (1 * minute) + 59;
                        break;
                    case 14: time = (2 * minute) + 6;
                        break;
                    case 15: time = (2 * minute) + 11;
                        break;
                    case 16: time = (2 * minute) + 26;
                        break;
                    case 17: time = (2 * minute) + 36;
                        break;
                    case 18: time = (2 * minute) + 52;
                        break;
                    case 19: time = (2 * minute) + 56;
                        break;
                    case 20: time = (3 * minute) + 9;
                        break;
                    case 21: time = (3 * minute) + 17;
                        break;
                    case 22: time = (3 * minute) + 28;
                        break;
                    case 23: time = (3 * minute) + 41;
                        break;
                    case 24: time = (3 * minute) + 46;
                        break;
                    case 25: time = (3 * minute) + 52;
                        break;
                    case 26: time = (4 * minute) + 4;
                        break;
                    case 27: time = (4 * minute) + 9;
                        break;
                    case 28: time = (4 * minute) + 19;
                        break;
                    case 29: time = (4 * minute) + 34;
                        break;
                    case 30: time = (4 * minute) + 37;
                        break;
                    case 31: time = (4 * minute) + 46;
                        break;
                    case 32: time = (4 * minute) + 55;
                        break;
                    case 33: time = (5 * minute) + 0;
                        break;
                    case 34: time = (5 * minute) + 10;
                        break;
                    case 35: time = (5 * minute) + 16;
                        break;
                    case 36: time = (5 * minute) + 22;
                        break;
                    case 37: time = (5 * minute) + 34;
                        break;
                    case 38: time = (5 * minute) + 41;
                        break;
                    case 39: time = (5 * minute) + 50;
                        break;
                    case 40: time = (6 * minute) + 6;
                        break;
                    case 41: time = (6 * minute) + 12;
                        break;
                    case 42: time = (6 * minute) + 28;
                        break;
                    case 43: time = (6 * minute) + 40;
                        break;
                    case 44: time = (6 * minute) + 49;
                        break;
                    case 45: time = (6 * minute) + 59;
                        break;
                    case 46: time = (7 * minute) + 6;
                }

                break;
            case 2: bookOfDeuteronomy.removeAll();
            stage.addActor(bookOfDeuteronomy.getTable2());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 13;
                        break;
                    case 3: time = (0 * minute) + 15;
                        break;
                    case 4: time = (0 * minute) + 20;
                        break;
                    case 5: time = (0 * minute) + 32;
                        break;
                    case 6: time = (0 * minute) + 46;
                        break;
                    case 7: time = (0 * minute) + 54;
                        break;
                    case 8: time = (1 * minute) + 7;
                        break;
                    case 9: time = (1 * minute) + 20;
                        break;
                    case 10: time = (1 * minute) + 34;
                        break;
                    case 11: time = (1 * minute) + 41;
                        break;
                    case 12: time = (1 * minute) + 48;
                        break;
                    case 13: time = (2 * minute) + 6;
                        break;
                    case 14: time = (2 * minute) + 10;
                        break;
                    case 15: time = (2 * minute) + 24;
                        break;
                    case 16: time = (2 * minute) + 30;
                        break;
                    case 17: time = (2 * minute) + 35;
                        break;
                    case 18: time = (2 * minute) + 37;
                        break;
                    case 19: time = (2 * minute) + 41;
                        break;
                    case 20: time = (2 * minute) + 56;
                        break;
                    case 21: time = (3 * minute) + 5;
                        break;
                    case 22: time = (3 * minute) + 16;
                        break;
                    case 23: time = (3 * minute) + 30;
                        break;
                    case 24: time = (3 * minute) + 41;
                        break;
                    case 25: time = (3 * minute) + 57;
                        break;
                    case 26: time = (4 * minute) + 8;
                        break;
                    case 27: time = (4 * minute) + 17;
                        break;
                    case 28: time = (4 * minute) + 25;
                        break;
                    case 29: time = (4 * minute) + 34;
                        break;
                    case 30: time = (4 * minute) + 46;
                        break;
                    case 31: time = (4 * minute) + 58;
                        break;
                    case 32: time = (5 * minute) + 9;
                        break;
                    case 33: time = (5 * minute) + 13;
                        break;
                    case 34: time = (5 * minute) + 19;
                        break;
                    case 35: time = (5 * minute) + 28;
                        break;
                    case 36: time = (5 * minute) + 34;
                        break;
                    case 37: time = (5 * minute) + 48;
                }

                break;
            case 3: bookOfDeuteronomy.removeAll();
            stage.addActor(bookOfDeuteronomy.getTable3());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 12;
                        break;
                    case 3: time = (0 * minute) + 27;
                        break;
                    case 4: time = (0 * minute) + 38;
                        break;
                    case 5: time = (0 * minute) + 51;
                        break;
                    case 6: time = (0 * minute) + 59;
                        break;
                    case 7: time = (1 * minute) + 9;
                        break;
                    case 8: time = (1 * minute) + 13;
                        break;
                    case 9: time = (1 * minute) + 23;
                        break;
                    case 10: time = (1 * minute) + 29;
                        break;
                    case 11: time = (1 * minute) + 39;
                        break;
                    case 12: time = (1 * minute) + 58;
                        break;
                    case 13: time = (2 * minute) + 14;
                        break;
                    case 14: time = (2 * minute) + 27;
                        break;
                    case 15: time = (2 * minute) + 44;
                        break;
                    case 16: time = (2 * minute) + 46;
                        break;
                    case 17: time = (2 * minute) + 59;
                        break;
                    case 18: time = (3 * minute) + 11;
                        break;
                    case 19: time = (3 * minute) + 22;
                        break;
                    case 20: time = (3 * minute) + 30;
                        break;
                    case 21: time = (3 * minute) + 43;
                        break;
                    case 22: time = (3 * minute) + 56;
                        break;
                    case 23: time = (4 * minute) + 1;
                        break;
                    case 24: time = (4 * minute) + 4;
                        break;
                    case 25: time = (4 * minute) + 16;
                        break;
                    case 26: time = (4 * minute) + 23;
                        break;
                    case 27: time = (4 * minute) + 35;
                        break;
                    case 28: time = (4 * minute) + 47;
                        break;
                    case 29: time = (4 * minute) + 57;
                }

                break;
            case 4: bookOfDeuteronomy.removeAll();
            stage.addActor(bookOfDeuteronomy.getTable4());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 17;
                        break;
                    case 3: time = (0 * minute) + 26;
                        break;
                    case 4: time = (0 * minute) + 36;
                        break;
                    case 5: time = (0 * minute) + 40;
                        break;
                    case 6: time = (0 * minute) + 51;
                        break;
                    case 7: time = (1 * minute) + 7;
                        break;
                    case 8: time = (1 * minute) + 15;
                        break;
                    case 9: time = (1 * minute) + 24;
                        break;
                    case 10: time = (1 * minute) + 37;
                        break;
                    case 11: time = (1 * minute) + 56;
                        break;
                    case 12: time = (2 * minute) + 5;
                        break;
                    case 13: time = (2 * minute) + 14;
                        break;
                    case 14: time = (2 * minute) + 24;
                        break;
                    case 15: time = (2 * minute) + 33;
                        break;
                    case 16: time = (2 * minute) + 42;
                        break;
                    case 17: time = (2 * minute) + 51;
                        break;
                    case 18: time = (3 * minute) + 4;
                        break;
                    case 19: time = (3 * minute) + 20;
                        break;
                    case 20: time = (3 * minute) + 30;
                        break;
                    case 21: time = (3 * minute) + 42;
                        break;
                    case 22: time = (3 * minute) + 51;
                        break;
                    case 23: time = (4 * minute) + 2;
                        break;
                    case 24: time = (4 * minute) + 8;
                        break;
                    case 25: time = (4 * minute) + 24;
                        break;
                    case 26: time = (4 * minute) + 38;
                        break;
                    case 27: time = (4 * minute) + 39;
                        break;
                    case 28: time = (4 * minute) + 45;
                        break;
                    case 29: time = (4 * minute) + 55;
                        break;
                    case 30: time = (5 * minute) + 13;
                        break;
                    case 31: time = (5 * minute) + 14;
                        break;
                    case 32: time = (5 * minute) + 23;
                        break;
                    case 33: time = (5 * minute) + 41;
                        break;
                    case 34: time = (5 * minute) + 48;
                        break;
                    case 35: time = (6 * minute) + 9;
                        break;
                    case 36: time = (6 * minute) + 17;
                        break;
                    case 37: time = (6 * minute) + 28;
                        break;
                    case 38: time = (6 * minute) + 36;
                        break;
                    case 39: time = (6 * minute) + 47;
                        break;
                    case 40: time = (6 * minute) + 56;
                        break;
                    case 41: time = (7 * minute) + 12;
                        break;
                    case 42: time = (7 * minute) + 18;
                        break;
                    case 43: time = (7 * minute) + 33;
                        break;
                    case 44: time = (7 * minute) + 45;
                        break;
                    case 45: time = (7 * minute) + 49;
                        break;
                    case 46: time = (7 * minute) + 58;
                        break;
                    case 47: time = (8 * minute) + 11;
                        break;
                    case 48: time = (8 * minute) + 22;
                        break;
                    case 49: time = (8 * minute) + 30;
                }

                break;
            case 5: bookOfDeuteronomy.removeAll();
            stage.addActor(bookOfDeuteronomy.getTable5());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 16;
                        break;
                    case 3: time = (0 * minute) + 21;
                        break;
                    case 4: time = (0 * minute) + 27;
                        break;
                    case 5: time = (0 * minute) + 32;
                        break;
                    case 6: time = (0 * minute) + 44;
                        break;
                    case 7: time = (0 * minute) + 50;
                        break;
                    case 8: time = (0 * minute) + 53;
                        break;
                    case 9: time = (1 * minute) + 3;
                        break;
                    case 10: time = (1 * minute) + 17;
                        break;
                    case 11: time = (1 * minute) + 22;
                        break;
                    case 12: time = (1 * minute) + 31;
                        break;
                    case 13: time = (1 * minute) + 36;
                        break;
                    case 14: time = (1 * minute) + 40;
                        break;
                    case 15: time = (2 * minute) + 2;
                        break;
                    case 16: time = (2 * minute) + 17;
                        break;
                    case 17: time = (2 * minute) + 28;
                        break;
                    case 18: time = (2 * minute) + 31;
                        break;
                    case 19: time = (2 * minute) + 33;
                        break;
                    case 20: time = (2 * minute) + 35;
                        break;
                    case 21: time = (2 * minute) + 38;
                        break;
                    case 22: time = (2 * minute) + 51;
                        break;
                    case 23: time = (3 * minute) + 7;
                        break;
                    case 24: time = (3 * minute) + 18;
                        break;
                    case 25: time = (3 * minute) + 31;
                        break;
                    case 26: time = (3 * minute) + 40;
                        break;
                    case 27: time = (3 * minute) + 49;
                        break;
                    case 28: time = (4 * minute) + 58;
                        break;
                    case 29: time = (4 * minute) + 10;
                        break;
                    case 30: time = (4 * minute) + 20;
                        break;
                    case 31: time = (4 * minute) + 23;
                        break;
                    case 32: time = (4 * minute) + 35;
                        break;
                    case 33: time = (4 * minute) + 44;
                }

                break;
            case 6: bookOfDeuteronomy.removeAll();
            stage.addActor(bookOfDeuteronomy.getTable6());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 14;
                        break;
                    case 3: time = (0 * minute) + 28;
                        break;
                    case 4: time = (0 * minute) + 44;
                        break;
                    case 5: time = (0 * minute) + 48;
                        break;
                    case 6: time = (0 * minute) + 54;
                        break;
                    case 7: time = (0 * minute) + 59;
                        break;
                    case 8: time = (0 * minute) + 9;
                        break;
                    case 9: time = (1 * minute) + 15;
                        break;
                    case 10: time = (1 * minute) + 20;
                        break;
                    case 11: time = (1 * minute) + 32;
                        break;
                    case 12: time = (1 * minute) + 44;
                        break;
                    case 13: time = (1 * minute) + 51;
                        break;
                    case 14: time = (1 * minute) + 58;
                        break;
                    case 15: time = (2 * minute) + 3;
                        break;
                    case 16: time = (2 * minute) + 15;
                        break;
                    case 17: time = (2 * minute) + 20;
                        break;
                    case 18: time = (2 * minute) + 28;
                        break;
                    case 19: time = (2 * minute) + 40;
                        break;
                    case 20: time = (2 * minute) + 46;
                        break;
                    case 21: time = (2 * minute) + 57;
                        break;
                    case 22: time = (3 * minute) + 5;
                        break;
                    case 23: time = (3 * minute) + 15;
                        break;
                    case 24: time = (3 * minute) + 23;
                        break;
                    case 25: time = (3 * minute) + 31;
                }

                break;
            case 7: bookOfDeuteronomy.removeAll();
            stage.addActor(bookOfDeuteronomy.getTable7());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 24;
                        break;
                    case 3: time = (0 * minute) + 36;
                        break;
                    case 4: time = (0 * minute) + 42;
                        break;
                    case 5: time = (0 * minute) + 54;
                        break;
                    case 6: time = (1 * minute) + 6;
                        break;
                    case 7: time = (1 * minute) + 17;
                        break;
                    case 8: time = (1 * minute) + 26;
                        break;
                    case 9: time = (1 * minute) + 42;
                        break;
                    case 10: time = (1 * minute) + 52;
                        break;
                    case 11: time = (2 * minute) + 4;
                        break;
                    case 12: time = (2 * minute) + 10;
                        break;
                    case 13: time = (2 * minute) + 20;
                        break;
                    case 14: time = (2 * minute) + 37;
                        break;
                    case 15: time = (2 * minute) + 45;
                        break;
                    case 16: time = (2 * minute) + 55;
                        break;
                    case 17: time = (3 * minute) + 7;
                        break;
                    case 18: time = (3 * minute) + 12;
                        break;
                    case 19: time = (3 * minute) + 20;
                        break;
                    case 20: time = (3 * minute) + 35;
                        break;
                    case 21: time = (3 * minute) + 42;
                        break;
                    case 22: time = (3 * minute) + 49;
                        break;
                    case 23: time = (4 * minute) + 0;
                        break;
                    case 24: time = (4 * minute) + 7;
                        break;
                    case 25: time = (4 * minute) + 19;
                        break;
                    case 26: time = (4 * minute) + 32;
                }

                break;
            case 8: bookOfDeuteronomy.removeAll();
            stage.addActor(bookOfDeuteronomy.getTable8());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 14;
                        break;
                    case 3: time = (0 * minute) + 27;
                        break;
                    case 4: time = (0 * minute) + 44;
                        break;
                    case 5: time = (0 * minute) + 50;
                        break;
                    case 6: time = (0 * minute) + 56;
                        break;
                    case 7: time = (1 * minute) + 3;
                        break;
                    case 8: time = (1 * minute) + 13;
                        break;
                    case 9: time = (1 * minute) + 20;
                        break;
                    case 10: time = (1 * minute) + 31;
                        break;
                    case 11: time = (1 * minute) + 36;
                        break;
                    case 12: time = (1 * minute) + 46;
                        break;
                    case 13: time = (1 * minute) + 50;
                        break;
                    case 14: time = (1 * minute) + 58;
                        break;
                    case 15: time = (2 * minute) + 6;
                        break;
                    case 16: time = (2 * minute) + 18;
                        break;
                    case 17: time = (2 * minute) + 26;
                        break;
                    case 18: time = (2 * minute) + 35;
                        break;
                    case 19: time = (2 * minute) + 44;
                        break;
                    case 20: time = (2 * minute) + 54;
                }

                break;
            case 9: bookOfDeuteronomy.removeAll();
            stage.addActor(bookOfDeuteronomy.getTable9());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 16;
                        break;
                    case 3: time = (0 * minute) + 25;
                        break;
                    case 4: time = (0 * minute) + 41;
                        break;
                    case 5: time = (0 * minute) + 59;
                        break;
                    case 6: time = (1 * minute) + 20;
                        break;
                    case 7: time = (1 * minute) + 30;
                        break;
                    case 8: time = (1 * minute) + 44;
                        break;
                    case 9: time = (1 * minute) + 51;
                        break;
                    case 10: time = (2 * minute) + 4;
                        break;
                    case 11: time = (2 * minute) + 18;
                        break;
                    case 12: time = (2 * minute) + 24;
                        break;
                    case 13: time = (2 * minute) + 41;
                        break;
                    case 14: time = (2 * minute) + 50;
                        break;
                    case 15: time = (3 * minute) + 0;
                        break;
                    case 16: time = (3 * minute) + 8;
                        break;
                    case 17: time = (3 * minute) + 21;
                        break;
                    case 18: time = (3 * minute) + 28;
                        break;
                    case 19: time = (3 * minute) + 44;
                        break;
                    case 20: time = (3 * minute) + 53;
                        break;
                    case 21: time = (4 * minute) + 2;
                        break;
                    case 22: time = (4 * minute) + 16;
                        break;
                    case 23: time = (4 * minute) + 23;
                        break;
                    case 24: time = (4 * minute) + 37;
                        break;
                    case 25: time = (4 * minute) + 41;
                        break;
                    case 26: time = (4 * minute) + 49;
                        break;
                    case 27: time = (5 * minute) + 3;
                        break;
                    case 28: time = (5 * minute) + 12;
                        break;
                    case 29: time = (5 * minute) + 25;
                }

                break;
            case 10: bookOfDeuteronomy.removeAll();
            stage.addActor(bookOfDeuteronomy.getTable10());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 13;
                        break;
                    case 3: time = (0 * minute) + 21;
                        break;
                    case 4: time = (0 * minute) + 29;
                        break;
                    case 5: time = (0 * minute) + 42;
                        break;
                    case 6: time = (0 * minute) + 52;
                        break;
                    case 7: time = (1 * minute) + 7;
                        break;
                    case 8: time = (1 * minute) + 14;
                        break;
                    case 9: time = (1 * minute) + 27;
                        break;
                    case 10: time = (1 * minute) + 38;
                        break;
                    case 11: time = (1 * minute) + 50;
                        break;
                    case 12: time = (2 * minute) + 2;
                        break;
                    case 13: time = (2 * minute) + 16;
                        break;
                    case 14: time = (2 * minute) + 22;
                        break;
                    case 15: time = (2 * minute) + 29;
                        break;
                    case 16: time = (2 * minute) + 39;
                        break;
                    case 17: time = (2 * minute) + 44;
                        break;
                    case 18: time = (2 * minute) + 54;
                        break;
                    case 19: time = (3 * minute) + 2;
                        break;
                    case 20: time = (3 * minute) + 7;
                        break;
                    case 21: time = (3 * minute) + 14;
                        break;
                    case 22: time = (3 * minute) + 22;
                }

                break;
            case 11: bookOfDeuteronomy.removeAll();
            stage.addActor(bookOfDeuteronomy.getTable11());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 11;
                        break;
                    case 3: time = (0 * minute) + 24;
                        break;
                    case 4: time = (0 * minute) + 31;
                        break;
                    case 5: time = (0 * minute) + 45;
                        break;
                    case 6: time = (0 * minute) + 49;
                        break;
                    case 7: time = (1 * minute) + 4;
                        break;
                    case 8: time = (1 * minute) + 8;
                        break;
                    case 9: time = (1 * minute) + 18;
                        break;
                    case 10: time = (1 * minute) + 29;
                        break;
                    case 11: time = (1 * minute) + 39;
                        break;
                    case 12: time = (1 * minute) + 46;
                        break;
                    case 13: time = (1 * minute) + 55;
                        break;
                    case 14: time = (2 * minute) + 5;
                        break;
                    case 15: time = (2 * minute) + 15;
                        break;
                    case 16: time = (2 * minute) + 22;
                        break;
                    case 17: time = (2 * minute) + 29;
                        break;
                    case 18: time = (2 * minute) + 41;
                        break;
                    case 19: time = (2 * minute) + 53;
                        break;
                    case 20: time = (3 * minute) + 2;
                        break;
                    case 21: time = (3 * minute) + 7;
                        break;
                    case 22: time = (3 * minute) + 17;
                        break;
                    case 23: time = (3 * minute) + 28;
                        break;
                    case 24: time = (3 * minute) + 36;
                        break;
                    case 25: time = (3 * minute) + 49;
                        break;
                    case 26: time = (4 * minute) + 1;
                        break;
                    case 27: time = (4 * minute) + 7;
                        break;
                    case 28: time = (4 * minute) + 11;
                        break;
                    case 29: time = (4 * minute) + 23;
                        break;
                    case 30: time = (4 * minute) + 33;
                        break;
                    case 31: time = (4 * minute) + 45;
                        break;
                    case 32: time = (4 * minute) + 54;
                }

                break;
            case 12: bookOfDeuteronomy.removeAll();
            stage.addActor(bookOfDeuteronomy.getTable12());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 13;
                        break;
                    case 3: time = (0 * minute) + 25;
                        break;
                    case 4: time = (0 * minute) + 39;
                        break;
                    case 5: time = (0 * minute) + 41;
                        break;
                    case 6: time = (0 * minute) + 52;
                        break;
                    case 7: time = (1 * minute) + 7;
                        break;
                    case 8: time = (1 * minute) + 17;
                        break;
                    case 9: time = (1 * minute) + 24;
                        break;
                    case 10: time = (1 * minute) + 30;
                        break;
                    case 11: time = (1 * minute) + 41;
                        break;
                    case 12: time = (1 * minute) + 59;
                        break;
                    case 13: time = (2 * minute) + 13;
                        break;
                    case 14: time = (2 * minute) + 17;
                        break;
                    case 15: time = (2 * minute) + 28;
                        break;
                    case 16: time = (2 * minute) + 42;
                        break;
                    case 17: time = (2 * minute) + 49;
                        break;
                    case 18: time = (3 * minute) + 6;
                        break;
                    case 19: time = (3 * minute) + 22;
                        break;
                    case 20: time = (3 * minute) + 27;
                        break;
                    case 21: time = (3 * minute) + 36;
                        break;
                    case 22: time = (3 * minute) + 51;
                        break;
                    case 23: time = (3 * minute) + 59;
                        break;
                    case 24: time = (4 * minute) + 6;
                        break;
                    case 25: time = (4 * minute) + 11;
                        break;
                    case 26: time = (4 * minute) + 20;
                        break;
                    case 27: time = (4 * minute) + 27;
                        break;
                    case 28: time = (4 * minute) + 41;
                        break;
                    case 29: time = (4 * minute) + 52;
                        break;
                    case 30: time = (5 * minute) + 1;
                        break;
                    case 31: time = (5 * minute) + 16;
                        break;
                    case 32: time = (5 * minute) + 30;
                }

                break;
            case 13: bookOfDeuteronomy.removeAll();
            stage.addActor(bookOfDeuteronomy.getTable13());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 10;
                        break;
                    case 3: time = (0 * minute) + 19;
                        break;
                    case 4: time = (0 * minute) + 32;
                        break;
                    case 5: time = (0 * minute) + 41;
                        break;
                    case 6: time = (1 * minute) + 3;
                        break;
                    case 7: time = (1 * minute) + 20;
                        break;
                    case 8: time = (1 * minute) + 30;
                        break;
                    case 9: time = (1 * minute) + 40;
                        break;
                    case 10: time = (1 * minute) + 47;
                        break;
                    case 11: time = (1 * minute) + 58;
                        break;
                    case 12: time = (2 * minute) + 6;
                        break;
                    case 13: time = (2 * minute) + 11;
                        break;
                    case 14: time = (2 * minute) + 25;
                        break;
                    case 15: time = (2 * minute) + 37;
                        break;
                    case 16: time = (2 * minute) + 46;
                        break;
                    case 17: time = (3 * minute) + 3;
                        break;
                    case 18: time = (3 * minute) + 15;
                }

                break;
            case 14: bookOfDeuteronomy.removeAll();
            stage.addActor(bookOfDeuteronomy.getTable14());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 11;
                        break;
                    case 3: time = (0 * minute) + 23;
                        break;
                    case 4: time = (0 * minute) + 25;
                        break;
                    case 5: time = (0 * minute) + 29;
                        break;
                    case 6: time = (0 * minute) + 37;
                        break;
                    case 7: time = (0 * minute) + 43;
                        break;
                    case 8: time = (0 * minute) + 56;
                        break;
                    case 9: time = (1 * minute) + 6;
                        break;
                    case 10: time = (1 * minute) + 11;
                        break;
                    case 11: time = (1 * minute) + 16;
                        break;
                    case 12: time = (1 * minute) + 19;
                        break;
                    case 13: time = (1 * minute) + 24;
                        break;
                    case 14: time = (1 * minute) + 27;
                        break;
                    case 15: time = (1 * minute) + 30;
                        break;
                    case 16: time = (1 * minute) + 33;
                        break;
                    case 17: time = (1 * minute) + 37;
                        break;
                    case 18: time = (1 * minute) + 40;
                        break;
                    case 19: time = (1 * minute) + 45;
                        break;
                    case 20: time = (1 * minute) + 49;
                        break;
                    case 21: time = (1 * minute) + 53;
                        break;
                    case 22: time = (2 * minute) + 10;
                        break;
                    case 23: time = (2 * minute) + 16;
                        break;
                    case 24: time = (2 * minute) + 31;
                        break;
                    case 25: time = (2 * minute) + 45;
                        break;
                    case 26: time = (2 * minute) + 52;
                        break;
                    case 27: time = (3 * minute) + 7;
                        break;
                    case 28: time = (3 * minute) + 15;
                        break;
                    case 29: time = (3 * minute) + 25;
                }

                break;
            case 15: bookOfDeuteronomy.removeAll();
            stage.addActor(bookOfDeuteronomy.getTable15());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 7;
                        break;
                    case 3: time = (0 * minute) + 20;
                        break;
                    case 4: time = (0 * minute) + 27;
                        break;
                    case 5: time = (0 * minute) + 35;
                        break;
                    case 6: time = (0 * minute) + 45;
                        break;
                    case 7: time = (1 * minute) + 0;
                        break;
                    case 8: time = (1 * minute) + 12;
                        break;
                    case 9: time = (1 * minute) + 19;
                        break;
                    case 10: time = (1 * minute) + 36;
                        break;
                    case 11: time = (1 * minute) + 49;
                        break;
                    case 12: time = (1 * minute) + 59;
                        break;
                    case 13: time = (2 * minute) + 10;
                        break;
                    case 14: time = (2 * minute) + 15;
                        break;
                    case 15: time = (2 * minute) + 26;
                        break;
                    case 16: time = (2 * minute) + 35;
                        break;
                    case 17: time = (2 * minute) + 44;
                        break;
                    case 18: time = (2 * minute) + 54;
                        break;
                    case 19: time = (3 * minute) + 7;
                        break;
                    case 20: time = (3 * minute) + 19;
                        break;
                    case 21: time = (3 * minute) + 27;
                        break;
                    case 22: time = (3 * minute) + 37;
                        break;
                    case 23: time = (3 * minute) + 45;
                }

                break;
            case 16: bookOfDeuteronomy.removeAll();
            stage.addActor(bookOfDeuteronomy.getTable16());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 14;
                        break;
                    case 3: time = (0 * minute) + 24;
                        break;
                    case 4: time = (0 * minute) + 41;
                        break;
                    case 5: time = (0 * minute) + 53;
                        break;
                    case 6: time = (0 * minute) + 59;
                        break;
                    case 7: time = (1 * minute) + 13;
                        break;
                    case 8: time = (1 * minute) + 21;
                        break;
                    case 9: time = (1 * minute) + 20;
                        break;
                    case 10: time = (1 * minute) + 39;
                        break;
                    case 11: time = (1 * minute) + 49;
                        break;
                    case 12: time = (2 * minute) + 8;
                        break;
                    case 13: time = (2 * minute) + 16;
                        break;
                    case 14: time = (2 * minute) + 25;
                        break;
                    case 15: time = (2 * minute) + 38;
                        break;
                    case 16: time = (2 * minute) + 52;
                        break;
                    case 17: time = (3 * minute) + 9;
                        break;
                    case 18: time = (3 * minute) + 16;
                        break;
                    case 19: time = (3 * minute) + 27;
                        break;
                    case 20: time = (3 * minute) + 39;
                        break;
                    case 21: time = (3 * minute) + 47;
                        break;
                    case 22: time = (3 * minute) + 55;
                }

                break;
            case 17: bookOfDeuteronomy.removeAll();
            stage.addActor(bookOfDeuteronomy.getTable17());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 14;
                        break;
                    case 3: time = (0 * minute) + 25;
                        break;
                    case 4: time = (0 * minute) + 34;
                        break;
                    case 5: time = (0 * minute) + 45;
                        break;
                    case 6: time = (0 * minute) + 55;
                        break;
                    case 7: time = (1 * minute) + 7;
                        break;
                    case 8: time = (1 * minute) + 17;
                        break;
                    case 9: time = (1 * minute) + 36;
                        break;
                    case 10: time = (1 * minute) + 47;
                        break;
                    case 11: time = (1 * minute) + 57;
                        break;
                    case 12: time = (2 * minute) + 13;
                        break;
                    case 13: time = (2 * minute) + 26;
                        break;
                    case 14: time = (2 * minute) + 31;
                        break;
                    case 15: time = (2 * minute) + 43;
                        break;
                    case 16: time = (2 * minute) + 55;
                        break;
                    case 17: time = (3 * minute) + 10;
                        break;
                    case 18: time = (3 * minute) + 19;
                        break;
                    case 19: time = (3 * minute) + 28;
                        break;
                    case 20: time = (3 * minute) + 41;
                }

                break;
            case 18: bookOfDeuteronomy.removeAll();
            stage.addActor(bookOfDeuteronomy.getTable18());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 14;
                        break;
                    case 3: time = (0 * minute) + 21;
                        break;
                    case 4: time = (0 * minute) + 33;
                        break;
                    case 5: time = (0 * minute) + 40;
                        break;
                    case 6: time = (0 * minute) + 49;
                        break;
                    case 7: time = (1 * minute) + 0;
                        break;
                    case 8: time = (1 * minute) + 7;
                        break;
                    case 9: time = (1 * minute) + 14;
                        break;
                    case 10: time = (1 * minute) + 23;
                        break;
                    case 11: time = (1 * minute) + 38;
                        break;
                    case 12: time = (1 * minute) + 44;
                        break;
                    case 13: time = (1 * minute) + 55;
                        break;
                    case 14: time = (1 * minute) + 58;
                        break;
                    case 15: time = (2 * minute) + 10;
                        break;
                    case 16: time = (2 * minute) + 18;
                        break;
                    case 17: time = (2 * minute) + 30;
                        break;
                    case 18: time = (2 * minute) + 35;
                        break;
                    case 19: time = (2 * minute) + 46;
                        break;
                    case 20: time = (2 * minute) + 54;
                        break;
                    case 21: time = (3 * minute) + 6;
                        break;
                    case 22: time = (3 * minute) + 12;
                }

                break;
            case 19: bookOfDeuteronomy.removeAll();
            stage.addActor(bookOfDeuteronomy.getTable19());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 13;
                        break;
                    case 3: time = (0 * minute) + 20;
                        break;
                    case 4: time = (0 * minute) + 31;
                        break;
                    case 5: time = (0 * minute) + 42;
                        break;
                    case 6: time = (0 * minute) + 56;
                        break;
                    case 7: time = (1 * minute) + 10;
                        break;
                    case 8: time = (1 * minute) + 14;
                        break;
                    case 9: time = (1 * minute) + 23;
                        break;
                    case 10: time = (1 * minute) + 36;
                        break;
                    case 11: time = (1 * minute) + 45;
                        break;
                    case 12: time = (1 * minute) + 55;
                        break;
                    case 13: time = (2 * minute) + 4;
                        break;
                    case 14: time = (2 * minute) + 12;
                        break;
                    case 15: time = (2 * minute) + 22;
                        break;
                    case 16: time = (2 * minute) + 37;
                        break;
                    case 17: time = (2 * minute) + 42;
                        break;
                    case 18: time = (2 * minute) + 50;
                        break;
                    case 19: time = (2 * minute) + 58;
                        break;
                    case 20: time = (3 * minute) + 4;
                        break;
                    case 21: time = (3 * minute) + 11;
                }

                break;
            case 20: bookOfDeuteronomy.removeAll();
            stage.addActor(bookOfDeuteronomy.getTable20());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 17;
                        break;
                    case 3: time = (0 * minute) + 22;
                        break;
                    case 4: time = (0 * minute) + 37;
                        break;
                    case 5: time = (0 * minute) + 45;
                        break;
                    case 6: time = (0 * minute) + 59;
                        break;
                    case 7: time = (1 * minute) + 14;
                        break;
                    case 8: time = (1 * minute) + 26;
                        break;
                    case 9: time = (1 * minute) + 43;
                        break;
                    case 10: time = (1 * minute) + 48;
                        break;
                    case 11: time = (1 * minute) + 53;
                        break;
                    case 12: time = (2 * minute) + 3;
                        break;
                    case 13: time = (2 * minute) + 9;
                        break;
                    case 14: time = (2 * minute) + 15;
                        break;
                    case 15: time = (2 * minute) + 28;
                        break;
                    case 16: time = (2 * minute) + 34;
                        break;
                    case 17: time = (2 * minute) + 42;
                        break;
                    case 18: time = (2 * minute) + 54;
                        break;
                    case 19: time = (3 * minute) + 7;
                        break;
                    case 20: time = (3 * minute) + 25;
                }

                break;
            case 21: bookOfDeuteronomy.removeAll();
            stage.addActor(bookOfDeuteronomy.getTable21());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 14;
                        break;
                    case 3: time = (0 * minute) + 20;
                        break;
                    case 4: time = (0 * minute) + 28;
                        break;
                    case 5: time = (0 * minute) + 39;
                        break;
                    case 6: time = (0 * minute) + 54;
                        break;
                    case 7: time = (1 * minute) + 2;
                        break;
                    case 8: time = (1 * minute) + 9;
                        break;
                    case 9: time = (1 * minute) + 22;
                        break;
                    case 10: time = (1 * minute) + 30;
                        break;
                    case 11: time = (1 * minute) + 37;
                        break;
                    case 12: time = (1 * minute) + 43;
                        break;
                    case 13: time = (1 * minute) + 48;
                        break;
                    case 14: time = (2 * minute) + 3;
                        break;
                    case 15: time = (2 * minute) + 16;
                        break;
                    case 16: time = (2 * minute) + 28;
                        break;
                    case 17: time = (2 * minute) + 41;
                        break;
                    case 18: time = (2 * minute) + 58;
                        break;
                    case 19: time = (3 * minute) + 9;
                        break;
                    case 20: time = (3 * minute) + 19;
                        break;
                    case 21: time = (3 * minute) + 32;
                        break;
                    case 22: time = (3 * minute) + 43;
                        break;
                    case 23: time = (3 * minute) + 52;
                }

                break;
            case 22: bookOfDeuteronomy.removeAll();
            stage.addActor(bookOfDeuteronomy.getTable22());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 11;
                        break;
                    case 3: time = (0 * minute) + 25;
                        break;
                    case 4: time = (0 * minute) + 36;
                        break;
                    case 5: time = (0 * minute) + 46;
                        break;
                    case 6: time = (0 * minute) + 56;
                        break;
                    case 7: time = (1 * minute) + 10;
                        break;
                    case 8: time = (1 * minute) + 17;
                        break;
                    case 9: time = (1 * minute) + 28;
                        break;
                    case 10: time = (1 * minute) + 39;
                        break;
                    case 11: time = (1 * minute) + 44;
                        break;
                    case 12: time = (1 * minute) + 48;
                        break;
                    case 13: time = (1 * minute) + 55;
                        break;
                    case 14: time = (1 * minute) + 59;
                        break;
                    case 15: time = (2 * minute) + 10;
                        break;
                    case 16: time = (2 * minute) + 18;
                        break;
                    case 17: time = (2 * minute) + 26;
                        break;
                    case 18: time = (2 * minute) + 42;
                        break;
                    case 19: time = (2 * minute) + 47;
                        break;
                    case 20: time = (3 * minute) + 3;
                        break;
                    case 21: time = (3 * minute) + 10;
                        break;
                    case 22: time = (3 * minute) + 28;
                        break;
                    case 23: time = (3 * minute) + 39;
                        break;
                    case 24: time = (3 * minute) + 45;
                        break;
                    case 25: time = (4 * minute) + 4;
                        break;
                    case 26: time = (4 * minute) + 15;
                        break;
                    case 27: time = (4 * minute) + 26;
                        break;
                    case 28: time = (4 * minute) + 34;
                        break;
                    case 29: time = (4 * minute) + 41;
                }

                break;
            case 23: bookOfDeuteronomy.removeAll();
            stage.addActor(bookOfDeuteronomy.getTable23());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 11;
                        break;
                    case 3: time = (0 * minute) + 22;
                        break;
                    case 4: time = (0 * minute) + 34;
                        break;
                    case 5: time = (0 * minute) + 46;
                        break;
                    case 6: time = (0 * minute) + 57;
                        break;
                    case 7: time = (1 * minute) + 4;
                        break;
                    case 8: time = (1 * minute) + 13;
                        break;
                    case 9: time = (1 * minute) + 17;
                        break;
                    case 10: time = (1 * minute) + 23;
                        break;
                    case 11: time = (1 * minute) + 34;
                        break;
                    case 12: time = (1 * minute) + 42;
                        break;
                    case 13: time = (1 * minute) + 45;
                        break;
                    case 14: time = (1 * minute) + 56;
                        break;
                    case 15: time = (2 * minute) + 11;
                        break;
                    case 16: time = (2 * minute) + 16;
                        break;
                    case 17: time = (2 * minute) + 26;
                        break;
                    case 18: time = (2 * minute) + 35;
                        break;
                    case 19: time = (2 * minute) + 48;
                        break;
                    case 20: time = (2 * minute) + 58;
                        break;
                    case 21: time = (3 * minute) + 11;
                        break;
                    case 22: time = (3 * minute) + 21;
                        break;
                    case 23: time = (3 * minute) + 26;
                        break;
                    case 24: time = (3 * minute) + 35;
                        break;
                    case 25: time = (3 * minute) + 45;
                }

                break;
            case 24: bookOfDeuteronomy.removeAll();
            stage.addActor(bookOfDeuteronomy.getTable24());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 19;
                        break;
                    case 3: time = (0 * minute) + 22;
                        break;
                    case 4: time = (0 * minute) + 31;
                        break;
                    case 5: time = (0 * minute) + 48;
                        break;
                    case 6: time = (1 * minute) + 1;
                        break;
                    case 7: time = (1 * minute) + 9;
                        break;
                    case 8: time = (1 * minute) + 21;
                        break;
                    case 9: time = (1 * minute) + 33;
                        break;
                    case 10: time = (1 * minute) + 39;
                        break;
                    case 11: time = (1 * minute) + 46;
                        break;
                    case 12: time = (1 * minute) + 51;
                        break;
                    case 13: time = (1 * minute) + 55;
                        break;
                    case 14: time = (2 * minute) + 6;
                        break;
                    case 15: time = (2 * minute) + 16;
                        break;
                    case 16: time = (2 * minute) + 27;
                        break;
                    case 17: time = (2 * minute) + 37;
                        break;
                    case 18: time = (2 * minute) + 45;
                        break;
                    case 19: time = (2 * minute) + 54;
                        break;
                    case 20: time = (3 * minute) + 8;
                        break;
                    case 21: time = (3 * minute) + 15;
                        break;
                    case 22: time = (3 * minute) + 23;
                }

                break;
            case 25: bookOfDeuteronomy.removeAll();
            stage.addActor(bookOfDeuteronomy.getTable25());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 12;
                        break;
                    case 3: time = (0 * minute) + 23;
                        break;
                    case 4: time = (0 * minute) + 34;
                        break;
                    case 5: time = (0 * minute) + 38;
                        break;
                    case 6: time = (0 * minute) + 55;
                        break;
                    case 7: time = (1 * minute) + 3;
                        break;
                    case 8: time = (1 * minute) + 20;
                        break;
                    case 9: time = (1 * minute) + 28;
                        break;
                    case 10: time = (1 * minute) + 43;
                        break;
                    case 11: time = (1 * minute) + 50;
                        break;
                    case 12: time = (2 * minute) + 1;
                        break;
                    case 13: time = (2 * minute) + 6;
                        break;
                    case 14: time = (2 * minute) + 11;
                        break;
                    case 15: time = (2 * minute) + 16;
                        break;
                    case 16: time = (2 * minute) + 26;
                        break;
                    case 17: time = (2 * minute) + 32;
                        break;
                    case 18: time = (2 * minute) + 37;
                        break;
                    case 19: time = (2 * minute) + 46;
                }

                break;
            case 26: bookOfDeuteronomy.removeAll();
            stage.addActor(bookOfDeuteronomy.getTable26());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 11;
                        break;
                    case 3: time = (0 * minute) + 25;
                        break;
                    case 4: time = (0 * minute) + 37;
                        break;
                    case 5: time = (0 * minute) + 43;
                        break;
                    case 6: time = (0 * minute) + 59;
                        break;
                    case 7: time = (1 * minute) + 4;
                        break;
                    case 8: time = (1 * minute) + 15;
                        break;
                    case 9: time = (1 * minute) + 23;
                        break;
                    case 10: time = (1 * minute) + 29;
                        break;
                    case 11: time = (1 * minute) + 40;
                        break;
                    case 12: time = (1 * minute) + 50;
                        break;
                    case 13: time = (2 * minute) + 4;
                        break;
                    case 14: time = (2 * minute) + 23;
                        break;
                    case 15: time = (2 * minute) + 37;
                        break;
                    case 16: time = (2 * minute) + 49;
                        break;
                    case 17: time = (2 * minute) + 59;
                        break;
                    case 18: time = (3 * minute) + 10;
                        break;
                    case 19: time = (3 * minute) + 21;
                }

                break;
            case 27: bookOfDeuteronomy.removeAll();
            stage.addActor(bookOfDeuteronomy.getTable27());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 12;
                        break;
                    case 3: time = (0 * minute) + 22;
                        break;
                    case 4: time = (0 * minute) + 34;
                        break;
                    case 5: time = (0 * minute) + 44;
                        break;
                    case 6: time = (0 * minute) + 53;
                        break;
                    case 7: time = (1 * minute) + 1;
                        break;
                    case 8: time = (1 * minute) + 9;
                        break;
                    case 9: time = (1 * minute) + 15;
                        break;
                    case 10: time = (1 * minute) + 27;
                        break;
                    case 11: time = (1 * minute) + 36;
                        break;
                    case 12: time = (1 * minute) + 41;
                        break;
                    case 13: time = (1 * minute) + 54;
                        break;
                    case 14: time = (2 * minute) + 3;
                        break;
                    case 15: time = (2 * minute) + 9;
                        break;
                    case 16: time = (2 * minute) + 26;
                        break;
                    case 17: time = (2 * minute) + 35;
                        break;
                    case 18: time = (2 * minute) + 43;
                        break;
                    case 19: time = (2 * minute) + 52;
                        break;
                    case 20: time = (3 * minute) + 3;
                        break;
                    case 21: time = (3 * minute) + 16;
                        break;
                    case 22: time = (3 * minute) + 24;
                        break;
                    case 23: time = (3 * minute) + 35;
                        break;
                    case 24: time = (3 * minute) + 43;
                        break;
                    case 25: time = (3 * minute) + 52;
                        break;
                    case 26: time = (4 * minute) + 2;
                }

                break;
            case 28: bookOfDeuteronomy.removeAll();
            stage.addActor(bookOfDeuteronomy.getTable28());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 18;
                        break;
                    case 3: time = (0 * minute) + 26;
                        break;
                    case 4: time = (0 * minute) + 31;
                        break;
                    case 5: time = (0 * minute) + 41;
                        break;
                    case 6: time = (0 * minute) + 44;
                        break;
                    case 7: time = (0 * minute) + 50;
                        break;
                    case 8: time = (1 * minute) + 1;
                        break;
                    case 9: time = (1 * minute) + 10;
                        break;
                    case 10: time = (1 * minute) + 21;
                        break;
                    case 11: time = (1 * minute) + 29;
                        break;
                    case 12: time = (1 * minute) + 42;
                        break;
                    case 13: time = (1 * minute) + 56;
                        break;
                    case 14: time = (2 * minute) + 10;
                        break;
                    case 15: time = (2 * minute) + 20;
                        break;
                    case 16: time = (2 * minute) + 35;
                        break;
                    case 17: time = (2 * minute) + 40;
                        break;
                    case 18: time = (2 * minute) + 44;
                        break;
                    case 19: time = (2 * minute) + 51;
                        break;
                    case 20: time = (2 * minute) + 57;
                        break;
                    case 21: time = (3 * minute) + 11;
                        break;
                    case 22: time = (3 * minute) + 19;
                        break;
                    case 23: time = (3 * minute) + 31;
                        break;
                    case 24: time = (3 * minute) + 37;
                        break;
                    case 25: time = (3 * minute) + 44;
                        break;
                    case 26: time = (3 * minute) + 56;
                        break;
                    case 27: time = (4 * minute) + 5;
                        break;
                    case 28: time = (4 * minute) + 12;
                        break;
                    case 29: time = (4 * minute) + 18;
                        break;
                    case 30: time = (4 * minute) + 32;
                        break;
                    case 31: time = (4 * minute) + 45;
                        break;
                    case 32: time = (5 * minute) + 1;
                        break;
                    case 33: time = (5 * minute) + 13;
                        break;
                    case 34: time = (5 * minute) + 23;
                        break;
                    case 35: time = (5 * minute) + 27;
                        break;
                    case 36: time = (5 * minute) + 37;
                        break;
                    case 37: time = (5 * minute) + 50;
                        break;
                    case 38: time = (5 * minute) + 58;
                        break;
                    case 39: time = (6 * minute) + 5;
                        break;
                    case 40: time = (6 * minute) + 13;
                        break;
                    case 41: time = (6 * minute) + 23;
                        break;
                    case 42: time = (6 * minute) + 29;
                        break;
                    case 43: time = (6 * minute) + 34;
                        break;
                    case 44: time = (6 * minute) + 40;
                        break;
                    case 45: time = (6 * minute) + 47;
                        break;
                    case 46: time = (7 * minute) + 2;
                        break;
                    case 47: time = (7 * minute) + 7;
                        break;
                    case 48: time = (7 * minute) + 14;
                        break;
                    case 49: time = (7 * minute) + 28;
                        break;
                    case 50: time = (7 * minute) + 37;
                        break;
                    case 51: time = (7 * minute) + 43;
                        break;
                    case 52: time = (7 * minute) + 59;
                        break;
                    case 53: time = (8 * minute) + 15;
                        break;
                    case 54: time = (8 * minute) + 27;
                        break;
                    case 55: time = (8 * minute) + 37;
                        break;
                    case 56: time = (8 * minute) + 52;
                        break;
                    case 57: time = (9 * minute) + 7;
                        break;
                    case 58: time = (9 * minute) + 23;
                        break;
                    case 59: time = (9 * minute) + 32;
                        break;
                    case 60: time = (9 * minute) + 43;
                        break;
                    case 61: time = (9 * minute) + 51;
                        break;
                    case 62: time = (10 * minute) + 0;
                        break;
                    case 63: time = (10 * minute) + 10;
                        break;
                    case 64: time = (10 * minute) + 23;
                        break;
                    case 65: time = (10 * minute) + 37;
                        break;
                    case 66: time = (10 * minute) + 49;
                        break;
                    case 67: time = (10 * minute) + 58;
                        break;
                    case 68: time = (11 * minute) + 14;
                }

                break;
            case 29: bookOfDeuteronomy.removeAll();
            stage.addActor(bookOfDeuteronomy.getTable29());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 17;
                        break;
                    case 3: time = (0 * minute) + 31;
                        break;
                    case 4: time = (0 * minute) + 36;
                        break;
                    case 5: time = (0 * minute) + 45;
                        break;
                    case 6: time = (0 * minute) + 54;
                        break;
                    case 7: time = (1 * minute) + 2;
                        break;
                    case 8: time = (1 * minute) + 14;
                        break;
                    case 9: time = (1 * minute) + 22;
                        break;
                    case 10: time = (1 * minute) + 30;
                        break;
                    case 11: time = (1 * minute) + 40;
                        break;
                    case 12: time = (1 * minute) + 49;
                        break;
                    case 13: time = (1 * minute) + 57;
                        break;
                    case 14: time = (2 * minute) + 8;
                        break;
                    case 15: time = (2 * minute) + 12;
                        break;
                    case 16: time = (2 * minute) + 20;
                        break;
                    case 17: time = (2 * minute) + 27;
                        break;
                    case 18: time = (2 * minute) + 35;
                        break;
                    case 19: time = (2 * minute) + 52;
                        break;
                    case 20: time = (3 * minute) + 7;
                        break;
                    case 21: time = (3 * minute) + 22;
                        break;
                    case 22: time = (3 * minute) + 33;
                        break;
                    case 23: time = (3 * minute) + 46;
                        break;
                    case 24: time = (4 * minute) + 1;
                        break;
                    case 25: time = (4 * minute) + 12;
                        break;
                    case 26: time = (4 * minute) + 23;
                        break;
                    case 27: time = (4 * minute) + 31;
                        break;
                    case 28: time = (4 * minute) + 39;
                        break;
                    case 29: time = (4 * minute) + 49;
                }

                break;
            case 30: bookOfDeuteronomy.removeAll();
            stage.addActor(bookOfDeuteronomy.getTable30());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 14;
                        break;
                    case 3: time = (0 * minute) + 24;
                        break;
                    case 4: time = (0 * minute) + 34;
                        break;
                    case 5: time = (0 * minute) + 44;
                        break;
                    case 6: time = (0 * minute) + 55;
                        break;
                    case 7: time = (1 * minute) + 5;
                        break;
                    case 8: time = (1 * minute) + 10;
                        break;
                    case 9: time = (1 * minute) + 17;
                        break;
                    case 10: time = (1 * minute) + 32;
                        break;
                    case 11: time = (1 * minute) + 44;
                        break;
                    case 12: time = (1 * minute) + 51;
                        break;
                    case 13: time = (1 * minute) + 59;
                        break;
                    case 14: time = (2 * minute) + 8;
                        break;
                    case 15: time = (2 * minute) + 13;
                        break;
                    case 16: time = (2 * minute) + 20;
                        break;
                    case 17: time = (2 * minute) + 38;
                        break;
                    case 18: time = (2 * minute) + 47;
                        break;
                    case 19: time = (2 * minute) + 57;
                        break;
                    case 20: time = (3 * minute) + 11;
                }

                break;
            case 31: bookOfDeuteronomy.removeAll();
            stage.addActor(bookOfDeuteronomy.getTable31());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 9;
                        break;
                    case 3: time = (0 * minute) + 23;
                        break;
                    case 4: time = (0 * minute) + 36;
                        break;
                    case 5: time = (0 * minute) + 45;
                        break;
                    case 6: time = (0 * minute) + 52;
                        break;
                    case 7: time = (1 * minute) + 4;
                        break;
                    case 8: time = (1 * minute) + 21;
                        break;
                    case 9: time = (1 * minute) + 32;
                        break;
                    case 10: time = (1 * minute) + 44;
                        break;
                    case 11: time = (1 * minute) + 54;
                        break;
                    case 12: time = (2 * minute) + 4;
                        break;
                    case 13: time = (2 * minute) + 18;
                        break;
                    case 14: time = (2 * minute) + 30;
                        break;
                    case 15: time = (2 * minute) + 48;
                        break;
                    case 16: time = (2 * minute) + 54;
                        break;
                    case 17: time = (3 * minute) + 12;
                        break;
                    case 18: time = (3 * minute) + 32;
                        break;
                    case 19: time = (3 * minute) + 41;
                        break;
                    case 20: time = (3 * minute) + 51;
                        break;
                    case 21: time = (4 * minute) + 6;
                        break;
                    case 22: time = (4 * minute) + 22;
                        break;
                    case 23: time = (4 * minute) + 28;
                        break;
                    case 24: time = (4 * minute) + 42;
                        break;
                    case 25: time = (4 * minute) + 48;
                        break;
                    case 26: time = (4 * minute) + 54;
                        break;
                    case 27: time = (5 * minute) + 3;
                        break;
                    case 28: time = (5 * minute) + 17;
                        break;
                    case 29: time = (5 * minute) + 28;
                        break;
                    case 30: time = (5 * minute) + 46;
                }

                break;
            case 32: bookOfDeuteronomy.removeAll();
            stage.addActor(bookOfDeuteronomy.getTable32());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 10;
                        break;
                    case 3: time = (0 * minute) + 21;
                        break;
                    case 4: time = (0 * minute) + 26;
                        break;
                    case 5: time = (0 * minute) + 36;
                        break;
                    case 6: time = (0 * minute) + 45;
                        break;
                    case 7: time = (0 * minute) + 57;
                        break;
                    case 8: time = (1 * minute) + 7;
                        break;
                    case 9: time = (1 * minute) + 17;
                        break;
                    case 10: time = (1 * minute) + 22;
                        break;
                    case 11: time = (1 * minute) + 33;
                        break;
                    case 12: time = (1 * minute) + 42;
                        break;
                    case 13: time = (1 * minute) + 48;
                        break;
                    case 14: time = (1 * minute) + 58;
                        break;
                    case 15: time = (2 * minute) + 12;
                        break;
                    case 16: time = (2 * minute) + 23;
                        break;
                    case 17: time = (2 * minute) + 30;
                        break;
                    case 18: time = (2 * minute) + 40;
                        break;
                    case 19: time = (2 * minute) + 46;
                        break;
                    case 20: time = (2 * minute) + 53;
                        break;
                    case 21: time = (3 * minute) + 5;
                        break;
                    case 22: time = (3 * minute) + 19;
                        break;
                    case 23: time = (3 * minute) + 30;
                        break;
                    case 24: time = (3 * minute) + 36;
                        break;
                    case 25: time = (3 * minute) + 49;
                        break;
                    case 26: time = (3 * minute) + 58;
                        break;
                    case 27: time = (4 * minute) + 3;
                        break;
                    case 28: time = (4 * minute) + 15;
                        break;
                    case 29: time = (4 * minute) + 21;
                        break;
                    case 30: time = (4 * minute) + 27;
                        break;
                    case 31: time = (4 * minute) + 36;
                        break;
                    case 32: time = (4 * minute) + 42;
                        break;
                    case 33: time = (4 * minute) + 50;
                        break;
                    case 34: time = (4 * minute) + 56;
                        break;
                    case 35: time = (5 * minute) + 1;
                        break;
                    case 36: time = (5 * minute) + 11;
                        break;
                    case 37: time = (5 * minute) + 21;
                        break;
                    case 38: time = (5 * minute) + 26;
                        break;
                    case 39: time = (5 * minute) + 36;
                        break;
                    case 40: time = (5 * minute) + 50;
                        break;
                    case 41: time = (5 * minute) + 55;
                        break;
                    case 42: time = (6 * minute) + 5;
                        break;
                    case 43: time = (6 * minute) + 17;
                        break;
                    case 44: time = (6 * minute) + 32;
                        break;
                    case 45: time = (6 * minute) + 39;
                        break;
                    case 46: time = (6 * minute) + 43;
                        break;
                    case 47: time = (6 * minute) + 56;
                        break;
                    case 48: time = (7 * minute) + 7;
                        break;
                    case 49: time = (7 * minute) + 10;
                        break;
                    case 50: time = (7 * minute) + 23;
                        break;
                    case 51: time = (7 * minute) + 33;
                        break;
                    case 52: time = (7 * minute) + 46;
                }

                break;
            case 33: bookOfDeuteronomy.removeAll();
            stage.addActor(bookOfDeuteronomy.getTable33());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 11;
                        break;
                    case 3: time = (0 * minute) + 28;
                        break;
                    case 4: time = (0 * minute) + 39;
                        break;
                    case 5: time = (0 * minute) + 45;
                        break;
                    case 6: time = (0 * minute) + 55;
                        break;
                    case 7: time = (1 * minute) + 0;
                        break;
                    case 8: time = (1 * minute) + 16;
                        break;
                    case 9: time = (1 * minute) + 30;
                        break;
                    case 10: time = (1 * minute) + 42;
                        break;
                    case 11: time = (1 * minute) + 53;
                        break;
                    case 12: time = (2 * minute) + 7;
                        break;
                    case 13: time = (2 * minute) + 19;
                        break;
                    case 14: time = (2 * minute) + 29;
                        break;
                    case 15: time = (2 * minute) + 35;
                        break;
                    case 16: time = (2 * minute) + 43;
                        break;
                    case 17: time = (2 * minute) + 56;
                        break;
                    case 18: time = (3 * minute) + 14;
                        break;
                    case 19: time = (3 * minute) + 23;
                        break;
                    case 20: time = (3 * minute) + 34;
                        break;
                    case 21: time = (3 * minute) + 45;
                        break;
                    case 22: time = (4 * minute) + 0;
                        break;
                    case 23: time = (4 * minute) + 7;
                        break;
                    case 24: time = (4 * minute) + 19;
                        break;
                    case 25: time = (4 * minute) + 31;
                        break;
                    case 26: time = (4 * minute) + 38;
                        break;
                    case 27: time = (4 * minute) + 47;
                        break;
                    case 28: time = (5 * minute) + 0;
                        break;
                    case 29: time = (5 * minute) + 8;
                }

                break;
            case 34: bookOfDeuteronomy.removeAll();
            stage.addActor(bookOfDeuteronomy.getTable34());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 18;
                        break;
                    case 3: time = (0 * minute) + 27;
                        break;
                    case 4: time = (0 * minute) + 34;
                        break;
                    case 5: time = (0 * minute) + 49;
                        break;
                    case 6: time = (0 * minute) + 56;
                        break;
                    case 7: time = (1 * minute) + 6;
                        break;
                    case 8: time = (1 * minute) + 14;
                        break;
                    case 9: time = (1 * minute) + 26;
                        break;
                    case 10: time = (1 * minute) + 39;
                        break;
                    case 11: time = (1 * minute) + 47;
                        break;
                    case 12: time = (2 * minute) + 0;
                }

                break;
        }
    }

    public void render(){
        stage.draw();
    }

    public void dispose(){
        bookOfDeuteronomy.dispose();
    }
}
