package com.legendandroidgame.game.BibleBooks;

import com.badlogic.gdx.scenes.scene2d.Stage;

/**
 * Created by Patrick on 8/12/2017.
 */
public class JoshuaStack {

    private Stage stage;
    private float time;
    private float minute = 60;
    private BookOfJoshua bookOfJoshua;

    public JoshuaStack() {
        stage = new Stage();
        bookOfJoshua = new BookOfJoshua();
    }

    public void josSwitch(int chapter, int verse){
        switch (chapter){
            case 1: bookOfJoshua.removeAll();
            stage.addActor(bookOfJoshua.getTable1());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 11;
                        break;
                    case 3: time = (0 * minute) + 23;
                        break;
                    case 4: time = (0 * minute) + 30;
                        break;
                    case 5: time = (0 * minute) + 43;
                        break;
                    case 6: time = (0 * minute) + 56;
                        break;
                    case 7: time = (1 * minute) + 4;
                        break;
                    case 8: time = (1 * minute) + 19;
                        break;
                    case 9: time = (1 * minute) + 35;
                        break;
                    case 10: time = (1 * minute) + 47;
                        break;
                    case 11: time = (1 * minute) + 50;
                        break;
                    case 12: time = (2 * minute) + 3;
                        break;
                    case 13: time = (2 * minute) + 8;
                        break;
                    case 14: time = (2 * minute) + 18;
                        break;
                    case 15: time = (2 * minute) + 30;
                        break;
                    case 16: time = (2 * minute) + 49;
                        break;
                    case 17: time = (2 * minute) + 56;
                        break;
                    case 18: time = (3 * minute) + 7;
                }

                break;
            case 2: bookOfJoshua.removeAll();
            stage.addActor(bookOfJoshua.getTable2());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 17;
                        break;
                    case 3: time = (0 * minute) + 24;
                        break;
                    case 4: time = (0 * minute) + 35;
                        break;
                    case 5: time = (0 * minute) + 44;
                        break;
                    case 6: time = (0 * minute) + 54;
                        break;
                    case 7: time = (1 * minute) + 0;
                        break;
                    case 8: time = (1 * minute) + 7;
                        break;
                    case 9: time = (1 * minute) + 10;
                        break;
                    case 10: time = (1 * minute) + 19;
                        break;
                    case 11: time = (1 * minute) + 32;
                        break;
                    case 12: time = (1 * minute) + 42;
                        break;
                    case 13: time = (1 * minute) + 52;
                        break;
                    case 14: time = (2 * minute) + 1;
                        break;
                    case 15: time = (2 * minute) + 13;
                        break;
                    case 16: time = (2 * minute) + 19;
                        break;
                    case 17: time = (2 * minute) + 31;
                        break;
                    case 18: time = (2 * minute) + 38;
                        break;
                    case 19: time = (2 * minute) + 52;
                        break;
                    case 20: time = (3 * minute) + 9;
                        break;
                    case 21: time = (3 * minute) + 17;
                        break;
                    case 22: time = (3 * minute) + 26;
                        break;
                    case 23: time = (3 * minute) + 36;
                        break;
                    case 24: time = (3 * minute) + 44;
                }

                break;
            case 3: bookOfJoshua.removeAll();
            stage.addActor(bookOfJoshua.getTable3());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 12;
                        break;
                    case 3: time = (0 * minute) + 15;
                        break;
                    case 4: time = (0 * minute) + 27;
                        break;
                    case 5: time = (0 * minute) + 42;
                        break;
                    case 6: time = (0 * minute) + 50;
                        break;
                    case 7: time = (1 * minute) + 0;
                        break;
                    case 8: time = (1 * minute) + 12;
                        break;
                    case 9: time = (1 * minute) + 21;
                        break;
                    case 10: time = (1 * minute) + 28;
                        break;
                    case 11: time = (1 * minute) + 47;
                        break;
                    case 12: time = (1 * minute) + 53;
                        break;
                    case 13: time = (1 * minute) + 59;
                        break;
                    case 14: time = (2 * minute) + 16;
                        break;
                    case 15: time = (2 * minute) + 23;
                        break;
                    case 16: time = (2 * minute) + 35;
                        break;
                    case 17: time = (2 * minute) + 51;

                }

                break;
            case 4: bookOfJoshua.removeAll();
            stage.addActor(bookOfJoshua.getTable4());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 7;
                        break;
                    case 3: time = (0 * minute) + 11;
                        break;
                    case 4: time = (0 * minute) + 26;
                        break;
                    case 5: time = (0 * minute) + 32;
                        break;
                    case 6: time = (0 * minute) + 45;
                        break;
                    case 7: time = (0 * minute) + 53;
                        break;
                    case 8: time = (1 * minute) + 10;
                        break;
                    case 9: time = (1 * minute) + 26;
                        break;
                    case 10: time = (1 * minute) + 35;
                        break;
                    case 11: time = (1 * minute) + 48;
                        break;
                    case 12: time = (1 * minute) + 54;
                        break;
                    case 13: time = (2 * minute) + 3;
                        break;
                    case 14: time = (2 * minute) + 9;
                        break;
                    case 15: time = (2 * minute) + 18;
                        break;
                    case 16: time = (2 * minute) + 21;
                        break;
                    case 17: time = (2 * minute) + 26;
                        break;
                    case 18: time = (2 * minute) + 31;
                        break;
                    case 19: time = (2 * minute) + 45;
                        break;
                    case 20: time = (2 * minute) + 52;
                        break;
                    case 21: time = (2 * minute) + 57;
                        break;
                    case 22: time = (3 * minute) + 6;
                        break;
                    case 23: time = (3 * minute) + 12;
                        break;
                    case 24: time = (3 * minute) + 23;
                }

                break;
            case 5: bookOfJoshua.removeAll();
            stage.addActor(bookOfJoshua.getTable5());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 21;
                        break;
                    case 3: time = (0 * minute) + 29;
                        break;
                    case 4: time = (0 * minute) + 35;
                        break;
                    case 5: time = (0 * minute) + 46;
                        break;
                    case 6: time = (0 * minute) + 56;
                        break;
                    case 7: time = (1 * minute) + 14;
                        break;
                    case 8: time = (1 * minute) + 25;
                        break;
                    case 9: time = (1 * minute) + 30;
                        break;
                    case 10: time = (1 * minute) + 41;
                        break;
                    case 11: time = (1 * minute) + 51;
                        break;
                    case 12: time = (1 * minute) + 58;
                        break;
                    case 13: time = (0 * minute) + 8;
                        break;
                    case 14: time = (0 * minute) + 23;
                        break;
                    case 15: time = (0 * minute) + 38;
                }

                break;
            case 6: bookOfJoshua.removeAll();
            stage.addActor(bookOfJoshua.getTable6());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 10;
                        break;
                    case 3: time = (0 * minute) + 18;
                        break;
                    case 4: time = (0 * minute) + 25;
                        break;
                    case 5: time = (0 * minute) + 36;
                        break;
                    case 6: time = (0 * minute) + 52;
                        break;
                    case 7: time = (1 * minute) + 2;
                        break;
                    case 8: time = (1 * minute) + 12;
                        break;
                    case 9: time = (1 * minute) + 23;
                        break;
                    case 10: time = (1 * minute) + 32;
                        break;
                    case 11: time = (1 * minute) + 44;
                        break;
                    case 12: time = (1 * minute) + 53;
                        break;
                    case 13: time = (1 * minute) + 57;
                        break;
                    case 14: time = (2 * minute) + 14;
                        break;
                    case 15: time = (2 * minute) + 21;
                        break;
                    case 16: time = (2 * minute) + 31;
                        break;
                    case 17: time = (2 * minute) + 41;
                        break;
                    case 18: time = (2 * minute) + 53;
                        break;
                    case 19: time = (3 * minute) + 6;
                        break;
                    case 20: time = (3 * minute) + 15;
                        break;
                    case 21: time = (3 * minute) + 30;
                        break;
                    case 22: time = (3 * minute) + 39;
                        break;
                    case 23: time = (3 * minute) + 50;
                        break;
                    case 24: time = (4 * minute) + 1;
                        break;
                    case 25: time = (4 * minute) + 11;
                        break;
                    case 26: time = (4 * minute) + 24;
                        break;
                    case 27: time = (4 * minute) + 39;
                }

                break;
            case 7: bookOfJoshua.removeAll();
            stage.addActor(bookOfJoshua.getTable7());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 18;
                        break;
                    case 3: time = (0 * minute) + 29;
                        break;
                    case 4: time = (0 * minute) + 43;
                        break;
                    case 5: time = (0 * minute) + 49;
                        break;
                    case 6: time = (1 * minute) + 0;
                        break;
                    case 7: time = (1 * minute) + 10;
                        break;
                    case 8: time = (1 * minute) + 25;
                        break;
                    case 9: time = (1 * minute) + 30;
                        break;
                    case 10: time = (1 * minute) + 40;
                        break;
                    case 11: time = (1 * minute) + 45;
                        break;
                    case 12: time = (1 * minute) + 58;
                        break;
                    case 13: time = (2 * minute) + 13;
                        break;
                    case 14: time = (2 * minute) + 31;
                        break;
                    case 15: time = (2 * minute) + 48;
                        break;
                    case 16: time = (3 * minute) + 2;
                        break;
                    case 17: time = (3 * minute) + 9;
                        break;
                    case 18: time = (3 * minute) + 13;
                        break;
                    case 19: time = (3 * minute) + 27;
                        break;
                    case 20: time = (3 * minute) + 40;
                        break;
                    case 21: time = (3 * minute) + 47;
                        break;
                    case 22: time = (4 * minute) + 6;
                        break;
                    case 23: time = (4 * minute) + 13;
                        break;
                    case 24: time = (4 * minute) + 20;
                        break;
                    case 25: time = (4 * minute) + 36;
                        break;
                    case 26: time = (4 * minute) + 49;
                }

                break;
            case 8: bookOfJoshua.removeAll();
            stage.addActor(bookOfJoshua.getTable8());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 19;
                        break;
                    case 3: time = (0 * minute) + 33;
                        break;
                    case 4: time = (0 * minute) + 43;
                        break;
                    case 5: time = (0 * minute) + 51;
                        break;
                    case 6: time = (1 * minute) + 1;
                        break;
                    case 7: time = (1 * minute) + 11;
                        break;
                    case 8: time = (1 * minute) + 17;
                        break;
                    case 9: time = (1 * minute) + 26;
                        break;
                    case 10: time = (1 * minute) + 36;
                        break;
                    case 11: time = (1 * minute) + 44;
                        break;
                    case 12: time = (1 * minute) + 52;
                        break;
                    case 13: time = (1 * minute) + 59;
                        break;
                    case 14: time = (2 * minute) + 9;
                        break;
                    case 15: time = (2 * minute) + 23;
                        break;
                    case 16: time = (2 * minute) + 29;
                        break;
                    case 17: time = (2 * minute) + 36;
                        break;
                    case 18: time = (2 * minute) + 44;
                        break;
                    case 19: time = (2 * minute) + 58;
                        break;
                    case 20: time = (3 * minute) + 8;
                        break;
                    case 21: time = (3 * minute) + 19;
                        break;
                    case 22: time = (3 * minute) + 29;
                        break;
                    case 23: time = (3 * minute) + 41;
                        break;
                    case 24: time = (3 * minute) + 45;
                        break;
                    case 25: time = (3 * minute) + 59;
                        break;
                    case 26: time = (4 * minute) + 6;
                        break;
                    case 27: time = (4 * minute) + 13;
                        break;
                    case 28: time = (4 * minute) + 21;
                        break;
                    case 29: time = (4 * minute) + 27;
                        break;
                    case 30: time = (4 * minute) + 42;
                        break;
                    case 31: time = (4 * minute) + 48;
                        break;
                    case 32: time = (5 * minute) + 4;
                        break;
                    case 33: time = (5 * minute) + 12;
                        break;
                    case 34: time = (5 * minute) + 34;
                        break;
                    case 35: time = (5 * minute) + 41;
                }

                break;
            case 9: bookOfJoshua.removeAll();
            stage.addActor(bookOfJoshua.getTable9());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 17;
                        break;
                    case 3: time = (0 * minute) + 21;
                        break;
                    case 4: time = (0 * minute) + 26;
                        break;
                    case 5: time = (0 * minute) + 36;
                        break;
                    case 6: time = (0 * minute) + 43;
                        break;
                    case 7: time = (0 * minute) + 53;
                        break;
                    case 8: time = (1 * minute) + 1;
                        break;
                    case 9: time = (1 * minute) + 10;
                        break;
                    case 10: time = (1 * minute) + 23;
                        break;
                    case 11: time = (1 * minute) + 36;
                        break;
                    case 12: time = (1 * minute) + 50;
                        break;
                    case 13: time = (2 * minute) + 3;
                        break;
                    case 14: time = (2 * minute) + 16;
                        break;
                    case 15: time = (2 * minute) + 20;
                        break;
                    case 16: time = (2 * minute) + 28;
                        break;
                    case 17: time = (2 * minute) + 35;
                        break;
                    case 18: time = (2 * minute) + 45;
                        break;
                    case 19: time = (2 * minute) + 57;
                        break;
                    case 20: time = (3 * minute) + 4;
                        break;
                    case 21: time = (3 * minute) + 11;
                        break;
                    case 22: time = (3 * minute) + 21;
                        break;
                    case 23: time = (3 * minute) + 30;
                        break;
                    case 24: time = (3 * minute) + 40;
                        break;
                    case 25: time = (3 * minute) + 58;
                        break;
                    case 26: time = (4 * minute) + 7;
                        break;
                    case 27: time = (4 * minute) + 13;
                }

                break;
            case 10: bookOfJoshua.removeAll();
            stage.addActor(bookOfJoshua.getTable10());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 18;
                        break;
                    case 3: time = (0 * minute) + 28;
                        break;
                    case 4: time = (0 * minute) + 39;
                        break;
                    case 5: time = (0 * minute) + 48;
                        break;
                    case 6: time = (1 * minute) + 2;
                        break;
                    case 7: time = (1 * minute) + 17;
                        break;
                    case 8: time = (1 * minute) + 23;
                        break;
                    case 9: time = (1 * minute) + 33;
                        break;
                    case 10: time = (1 * minute) + 39;
                        break;
                    case 11: time = (1 * minute) + 49;
                        break;
                    case 12: time = (2 * minute) + 5;
                        break;
                    case 13: time = (2 * minute) + 21;
                        break;
                    case 14: time = (2 * minute) + 36;
                        break;
                    case 15: time = (2 * minute) + 43;
                        break;
                    case 16: time = (2 * minute) + 48;
                        break;
                    case 17: time = (2 * minute) + 52;
                        break;
                    case 18: time = (2 * minute) + 58;
                        break;
                    case 19: time = (3 * minute) + 4;
                        break;
                    case 20: time = (3 * minute) + 14;
                        break;
                    case 21: time = (3 * minute) + 24;
                        break;
                    case 22: time = (3 * minute) + 32;
                        break;
                    case 23: time = (3 * minute) + 39;
                        break;
                    case 24: time = (3* minute) + 49;
                        break;
                    case 25: time = (4 * minute) + 5;
                        break;
                    case 26: time = (4 * minute) + 16;
                        break;
                    case 27: time = (4 * minute) + 24;
                        break;
                    case 28: time = (4 * minute) + 38;
                        break;
                    case 29: time = (4 * minute) + 54;
                        break;
                    case 30: time = (5 * minute) + 0;
                        break;
                    case 31: time = (5 * minute) + 13;
                        break;
                    case 32: time = (5 * minute) + 21;
                        break;
                    case 33: time = (5 * minute) + 30;
                        break;
                    case 34: time = (5 * minute) + 38;
                        break;
                    case 35: time = (5 * minute) + 47;
                        break;
                    case 36: time = (5 * minute) + 56;
                        break;
                    case 37: time = (6 * minute) + 1;
                        break;
                    case 38: time = (6 * minute) + 14;
                        break;
                    case 39: time = (6 * minute) + 18;
                        break;
                    case 40: time = (6 * minute) + 34;
                        break;
                    case 41: time = (6 * minute) + 47;
                        break;
                    case 42: time = (6 * minute) + 54;
                        break;
                    case 43: time = (7 * minute) + 1;
                }

                break;
            case 11: bookOfJoshua.removeAll();
            stage.addActor(bookOfJoshua.getTable11());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 10;
                        break;
                    case 3: time = (0 * minute) + 19;
                        break;
                    case 4: time = (0 * minute) + 29;
                        break;
                    case 5: time = (0 * minute) + 37;
                        break;
                    case 6: time = (0 * minute) + 44;
                        break;
                    case 7: time = (0 * minute) + 59;
                        break;
                    case 8: time = (1 * minute) + 5;
                        break;
                    case 9: time = (1 * minute) + 18;
                        break;
                    case 10: time = (1 * minute) + 24;
                        break;
                    case 11: time = (1 * minute) + 33;
                        break;
                    case 12: time = (1 * minute) + 41;
                        break;
                    case 13: time = (1 * minute) + 52;
                        break;
                    case 14: time = (1 * minute) + 58;
                        break;
                    case 15: time = (2 * minute) + 10;
                        break;
                    case 16: time = (2 * minute) + 21;
                        break;
                    case 17: time = (2 * minute) + 31;
                        break;
                    case 18: time = (2 * minute) + 42;
                        break;
                    case 19: time = (2 * minute) + 46;
                        break;
                    case 20: time = (2 * minute) + 53;
                        break;
                    case 21: time = (3 * minute) + 7;
                        break;
                    case 22: time = (3 * minute) + 20;
                        break;
                    case 23: time = (3 * minute) + 28;
                }

                break;
            case 12: bookOfJoshua.removeAll();
            stage.addActor(bookOfJoshua.getTable12());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 14;
                        break;
                    case 3: time = (0 * minute) + 27;
                        break;
                    case 4: time = (0 * minute) + 37;
                        break;
                    case 5: time = (0 * minute) + 44;
                        break;
                    case 6: time = (0 * minute) + 54;
                        break;
                    case 7: time = (1 * minute) + 7;
                        break;
                    case 8: time = (1 * minute) + 22;
                        break;
                    case 9: time = (1 * minute) + 34;
                        break;
                    case 10: time = (1 * minute) + 40;
                        break;
                    case 11: time = (1 * minute) + 44;
                        break;
                    case 12: time = (1 * minute) + 48;
                        break;
                    case 13: time = (1 * minute) + 52;
                        break;
                    case 14: time = (1 * minute) + 56;
                        break;
                    case 15: time = (2 * minute) + 0;
                        break;
                    case 16: time = (2 * minute) + 4;
                        break;
                    case 17: time = (2 * minute) + 8;
                        break;
                    case 18: time = (2 * minute) + 12;
                        break;
                    case 19: time = (2 * minute) + 17;
                        break;
                    case 20: time = (2 * minute) + 21;
                        break;
                    case 21: time = (2 * minute) + 27;
                        break;
                    case 22: time = (2 * minute) + 31;
                        break;
                    case 23: time = (2 * minute) + 37;
                        break;
                    case 24: time = (2 * minute) + 42;
                        break;
                }

                break;
            case 13: bookOfJoshua.removeAll();
            stage.addActor(bookOfJoshua.getTable13());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 14;
                        break;
                    case 3: time = (0 * minute) + 22;
                        break;
                    case 4: time = (0 * minute) + 36;
                        break;
                    case 5: time = (0 * minute) + 45;
                        break;
                    case 6: time = (0 * minute) + 51;
                        break;
                    case 7: time = (1 * minute) + 7;
                        break;
                    case 8: time = (1 * minute) + 14;
                        break;
                    case 9: time = (1 * minute) + 26;
                        break;
                    case 10: time = (1 * minute) + 35;
                        break;
                    case 11: time = (1 * minute) + 41;
                        break;
                    case 12: time = (1 * minute) + 49;
                        break;
                    case 13: time = (1 * minute) + 59;
                        break;
                    case 14: time = (2 * minute) + 8;
                        break;
                    case 15: time = (2 * minute) + 16;
                        break;
                    case 16: time = (2 * minute) + 22;
                        break;
                    case 17: time = (2 * minute) + 32;
                        break;
                    case 18: time = (2 * minute) + 38;
                        break;
                    case 19: time = (2 * minute) + 41;
                        break;
                    case 20: time = (2 * minute) + 46;
                        break;
                    case 21: time = (2 * minute) + 50;
                        break;
                    case 22: time = (3 * minute) + 6;
                        break;
                    case 23: time = (3 * minute) + 15;
                        break;
                    case 24: time = (3 * minute) + 25;
                        break;
                    case 25: time = (3 * minute) + 32;
                        break;
                    case 26: time = (3 * minute) + 39;
                        break;
                    case 27: time = (3 * minute) + 44;
                        break;
                    case 28: time = (3 * minute) + 59;
                        break;
                    case 29: time = (4 * minute) + 4;
                        break;
                    case 30: time = (4 * minute) + 13;
                        break;
                    case 31: time = (4 * minute) + 23;
                        break;
                    case 32: time = (4 * minute) + 36;
                        break;
                    case 33: time = (4 * minute) + 43;
                }

                break;
            case 14: bookOfJoshua.removeAll();
            stage.addActor(bookOfJoshua.getTable14());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 16;
                        break;
                    case 3: time = (0 * minute) + 24;
                        break;
                    case 4: time = (0 * minute) + 31;
                        break;
                    case 5: time = (0 * minute) + 43;
                        break;
                    case 6: time = (0 * minute) + 48;
                        break;
                    case 7: time = (1 * minute) + 1;
                        break;
                    case 8: time = (1 * minute) + 11;
                        break;
                    case 9: time = (1 * minute) + 19;
                        break;
                    case 10: time = (1 * minute) + 32;
                        break;
                    case 11: time = (1 * minute) + 51;
                        break;
                    case 12: time = (2 * minute) + 2;
                        break;
                    case 13: time = (2 * minute) + 21;
                        break;
                    case 14: time = (2 * minute) + 27;
                        break;
                    case 15: time = (2 * minute) + 37;
                }

                break;
            case 15: bookOfJoshua.removeAll();
            stage.addActor(bookOfJoshua.getTable15());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 12;
                        break;
                    case 3: time = (0 * minute) + 19;
                        break;
                    case 4: time = (0 * minute) + 30;
                        break;
                    case 5: time = (0 * minute) + 39;
                        break;
                    case 6: time = (0 * minute) + 53;
                        break;
                    case 7: time = (0 * minute) + 56;
                        break;
                    case 8: time = (1 * minute) + 11;
                        break;
                    case 9: time = (1 * minute) + 26;
                        break;
                    case 10: time = (1 * minute) + 38;
                        break;
                    case 11: time = (1 * minute) + 50;
                        break;
                    case 12: time = (2 * minute) + 3;
                        break;
                    case 13: time = (2 * minute) + 11;
                        break;
                    case 14: time = (2 * minute) + 23;
                        break;
                    case 15: time = (2 * minute) + 30;
                        break;
                    case 16: time = (2 * minute) + 37;
                        break;
                    case 17: time = (2 * minute) + 47;
                        break;
                    case 18: time = (2 * minute) + 54;
                        break;
                    case 19: time = (3 * minute) + 2;
                        break;
                    case 20: time = (3 * minute) + 14;
                        break;
                    case 21: time = (3 * minute) + 18;
                        break;
                    case 22: time = (3 * minute) + 27;
                        break;
                    case 23: time = (3 * minute) + 29;
                        break;
                    case 24: time = (3 * minute) + 32;
                        break;
                    case 25: time = (3 * minute) + 34;
                        break;
                    case 26: time = (3 * minute) + 38;
                        break;
                    case 27: time = (3 * minute) + 41;
                        break;
                    case 28: time = (3 * minute) + 44;
                        break;
                    case 29: time = (3 * minute) + 48;
                        break;
                    case 30: time = (3 * minute) + 51;
                        break;
                    case 31: time = (3 * minute) + 55;
                        break;
                    case 32: time = (3 * minute) + 57;
                        break;
                    case 33: time = (4 * minute) + 5;
                        break;
                    case 34: time = (4 * minute) + 9;
                        break;
                    case 35: time = (4 * minute) + 14;
                        break;
                    case 36: time = (4 * minute) + 17;
                        break;
                    case 37: time = (4 * minute) + 24;
                        break;
                    case 38: time = (4 * minute) + 29;
                        break;
                    case 39: time = (4 * minute) + 32;
                        break;
                    case 40: time = (4 * minute) + 35;
                        break;
                    case 41: time = (4 * minute) + 37;
                        break;
                    case 42: time = (4 * minute) + 45;
                        break;
                    case 43: time = (4 * minute) + 47;
                        break;
                    case 44: time = (4 * minute) + 50;
                        break;
                    case 45: time = (4 * minute) + 55;
                        break;
                    case 46: time = (4 * minute) + 58;
                        break;
                    case 47: time = (5 * minute) + 3;
                        break;
                    case 48: time = (5 * minute) + 13;
                        break;
                    case 49: time = (5 * minute) + 17;
                        break;
                    case 50: time = (5 * minute) + 20;
                        break;
                    case 51: time = (5 * minute) + 23;
                        break;
                    case 52: time = (5 * minute) + 28;
                        break;
                    case 53: time = (5 * minute) + 31;
                        break;
                    case 54: time = (5 * minute) + 34;
                        break;
                    case 55: time = (5 * minute) + 41;
                        break;
                    case 56: time = (5 * minute) + 44;
                        break;
                    case 57: time = (5 * minute) + 48;
                        break;
                    case 58: time = (5 * minute) + 53;
                        break;
                    case 59: time = (5 * minute) + 56;
                        break;
                    case 60: time = (6 * minute) + 2;
                        break;
                    case 61: time = (6 * minute) + 8;
                        break;
                    case 62: time = (6 * minute) + 12;
                        break;
                    case 63: time = (6 * minute) + 18;
                }

                break;
            case 16: bookOfJoshua.removeAll();
            stage.addActor(bookOfJoshua.getTable16());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 13;
                        break;
                    case 3: time = (0 * minute) + 19;
                        break;
                    case 4: time = (0 * minute) + 29;
                        break;
                    case 5: time = (0 * minute) + 35;
                        break;
                    case 6: time = (0 * minute) + 44;
                        break;
                    case 7: time = (0 * minute) + 57;
                        break;
                    case 8: time = (1 * minute) + 3;
                        break;
                    case 9: time = (1 * minute) + 14;
                        break;
                    case 10: time = (1 * minute) + 22;
                }

                break;
            case 17: bookOfJoshua.removeAll();
            stage.addActor(bookOfJoshua.getTable17());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 16;
                        break;
                    case 3: time = (0 * minute) + 30;
                        break;
                    case 4: time = (0 * minute) + 46;
                        break;
                    case 5: time = (1 * minute) + 2;
                        break;
                    case 6: time = (1 * minute) + 10;
                        break;
                    case 7: time = (1 * minute) + 19;
                        break;
                    case 8: time = (1 * minute) + 28;
                        break;
                    case 9: time = (1 * minute) + 35;
                        break;
                    case 10: time = (1 * minute) + 48;
                        break;
                    case 11: time = (2 * minute) + 0;
                        break;
                    case 12: time = (2 * minute) + 22;
                        break;
                    case 13: time = (2 * minute) + 28;
                        break;
                    case 14: time = (2 * minute) + 35;
                        break;
                    case 15: time = (2 * minute) + 46;
                        break;
                    case 16: time = (3 * minute) + 0;
                        break;
                    case 17: time = (3 * minute) + 14;
                        break;
                    case 18: time = (3 * minute) + 23;
                }

                break;
            case 18: bookOfJoshua.removeAll();
            stage.addActor(bookOfJoshua.getTable18());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 11;
                        break;
                    case 3: time = (0 * minute) + 17;
                        break;
                    case 4: time = (0 * minute) + 26;
                        break;
                    case 5: time = (0 * minute) + 38;
                        break;
                    case 6: time = (0 * minute) + 49;
                        break;
                    case 7: time = (0 * minute) + 57;
                        break;
                    case 8: time = (1 * minute) + 12;
                        break;
                    case 9: time = (1 * minute) + 26;
                        break;
                    case 10: time = (1 * minute) + 37;
                        break;
                    case 11: time = (1 * minute) + 45;
                        break;
                    case 12: time = (1 * minute) + 56;
                        break;
                    case 13: time = (2 * minute) + 7;
                        break;
                    case 14: time = (2 * minute) + 20;
                        break;
                    case 15: time = (2 * minute) + 37;
                        break;
                    case 16: time = (2 * minute) + 45;
                        break;
                    case 17: time = (2 * minute) + 58;
                        break;
                    case 18: time = (3 * minute) + 11;
                        break;
                    case 19: time = (3 * minute) + 16;
                        break;
                    case 20: time = (3 * minute) + 27;
                        break;
                    case 21: time = (3 * minute) + 37;
                        break;
                    case 22: time = (3 * minute) + 45;
                        break;
                    case 23: time = (3 * minute) + 48;
                        break;
                    case 24: time = (3 * minute) + 51;
                        break;
                    case 25: time = (3 * minute) + 56;
                        break;
                    case 26: time = (4 * minute) + 0;
                        break;
                    case 27: time = (4 * minute) + 2;
                        break;
                    case 28: time = (4 * minute) + 6;
                }

                break;
            case 19: bookOfJoshua.removeAll();
            stage.addActor(bookOfJoshua.getTable19());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 13;
                        break;
                    case 3: time = (0 * minute) + 18;
                        break;
                    case 4: time = (0 * minute) + 21;
                        break;
                    case 5: time = (0 * minute) + 24;
                        break;
                    case 6: time = (0 * minute) + 27;
                        break;
                    case 7: time = (0 * minute) + 32;
                        break;
                    case 8: time = (0 * minute) + 38;
                        break;
                    case 9: time = (0 * minute) + 49;
                        break;
                    case 10: time = (1 * minute) + 2;
                        break;
                    case 11: time = (1 * minute) + 11;
                        break;
                    case 12: time = (1 * minute) + 18;
                        break;
                    case 13: time = (1 * minute) + 28;
                        break;
                    case 14: time = (1 * minute) + 36;
                        break;
                    case 15: time = (1 * minute) + 42;
                        break;
                    case 16: time = (1 * minute) + 49;
                        break;
                    case 17: time = (1 * minute) + 55;
                        break;
                    case 18: time = (2 * minute) + 1;
                        break;
                    case 19: time = (2 * minute) + 6;
                        break;
                    case 20: time = (2 * minute) + 10;
                        break;
                    case 21: time = (2 * minute) + 13;
                        break;
                    case 22: time = (2 * minute) + 17;
                        break;
                    case 23: time = (2 * minute) + 26;
                        break;
                    case 24: time = (2 * minute) + 33;
                        break;
                    case 25: time = (2 * minute) + 39;
                        break;
                    case 26: time = (2 * minute) + 44;
                        break;
                    case 27: time = (2 * minute) + 51;
                        break;
                    case 28: time = (3 * minute) + 2;
                        break;
                    case 29: time = (3 * minute) + 8;
                        break;
                    case 30: time = (3 * minute) + 17;
                        break;
                    case 31: time = (3 * minute) + 23;
                        break;
                    case 32: time = (3 * minute) + 30;
                        break;
                    case 33: time = (3 * minute) + 36;
                        break;
                    case 34: time = (3 * minute) + 45;
                        break;
                    case 35: time = (3 * minute) + 56;
                        break;
                    case 36: time = (4 * minute) + 2;
                        break;
                    case 37: time = (4 * minute) + 4;
                        break;
                    case 38: time = (4 * minute) + 8;
                        break;
                    case 39: time = (4 * minute) + 16;
                        break;
                    case 40: time = (4 * minute) + 23;
                        break;
                    case 41: time = (4 * minute) + 29;
                        break;
                    case 42: time = (4 * minute) + 34;
                        break;
                    case 43: time = (4 * minute) + 38;
                        break;
                    case 44: time = (4 * minute) + 40;
                        break;
                    case 45: time = (4 * minute) + 44;
                        break;
                    case 46: time = (4 * minute) + 47;
                        break;
                    case 47: time = (4 * minute) + 52;
                        break;
                    case 48: time = (5 * minute) + 7;
                        break;
                    case 49: time = (5 * minute) + 15;
                        break;
                    case 50: time = (5 * minute) + 25;
                        break;
                    case 51: time = (5 * minute) + 33;
                }

                break;
            case 20: bookOfJoshua.removeAll();
            stage.addActor(bookOfJoshua.getTable20());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 5;
                        break;
                    case 3: time = (0 * minute) + 12;
                        break;
                    case 4: time = (0 * minute) + 22;
                        break;
                    case 5: time = (0 * minute) + 36;
                        break;
                    case 6: time = (0 * minute) + 47;
                        break;
                    case 7: time = (1 * minute) + 2;
                        break;
                    case 8: time = (1 * minute) + 14;
                        break;
                    case 9: time = (1 * minute) + 26;
                }

                break;
            case 21: bookOfJoshua.removeAll();
            stage.addActor(bookOfJoshua.getTable21());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 12;
                        break;
                    case 3: time = (0 * minute) + 22;
                        break;
                    case 4: time = (0 * minute) + 30;
                        break;
                    case 5: time = (0 * minute) + 41;
                        break;
                    case 6: time = (0 * minute) + 50;
                        break;
                    case 7: time = (1 * minute) + 0;
                        break;
                    case 8: time = (1 * minute) + 8;
                        break;
                    case 9: time = (1 * minute) + 15;
                        break;
                    case 10: time = (1 * minute) + 21;
                        break;
                    case 11: time = (1 * minute) + 30;
                        break;
                    case 12: time = (1 * minute) + 39;
                        break;
                    case 13: time = (1 * minute) + 45;
                        break;
                    case 14: time = (1 * minute) + 53;
                        break;
                    case 15: time = (1 * minute) + 58;
                        break;
                    case 16: time = (2 * minute) + 2;
                        break;
                    case 17: time = (2 * minute) + 10;
                        break;
                    case 18: time = (2 * minute) + 16;
                        break;
                    case 19: time = (2 * minute) + 22;
                        break;
                    case 20: time = (2 * minute) + 29;
                        break;
                    case 21: time = (2 * minute) + 36;
                        break;
                    case 22: time = (2 * minute) + 44;
                        break;
                    case 23: time = (2 * minute) + 50;
                        break;
                    case 24: time = (2 * minute) + 56;
                        break;
                    case 25: time = (3 * minute) + 2;
                        break;
                    case 26: time = (3 * minute) + 10;
                        break;
                    case 27: time = (3 * minute) + 15;
                        break;
                    case 28: time = (3 * minute) + 29;
                        break;
                    case 29: time = (3 * minute) + 35;
                        break;
                    case 30: time = (3 * minute) + 41;
                        break;
                    case 31: time = (3 * minute) + 47;
                        break;
                    case 32: time = (3 * minute) + 52;
                        break;
                    case 33: time = (4 * minute) + 5;
                        break;
                    case 34: time = (4 * minute) + 10;
                        break;
                    case 35: time = (4 * minute) + 20;
                        break;
                    case 36: time = (4 * minute) + 26;
                        break;
                    case 37: time = (4 * minute) + 31;
                        break;
                    case 38: time = (4 * minute) + 38;
                        break;
                    case 39: time = (4 * minute) + 47;
                        break;
                    case 40: time = (4 * minute) + 52;
                        break;
                    case 41: time = (5 * minute) + 1;
                        break;
                    case 42: time = (5 * minute) + 9;
                        break;
                    case 43: time = (5 * minute) + 14;
                        break;
                    case 44: time = (5 * minute) + 22;
                        break;
                    case 45: time = (5 * minute) + 34;
                }

                break;
            case 22: bookOfJoshua.removeAll();
            stage.addActor(bookOfJoshua.getTable22());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 8;
                        break;
                    case 3: time = (0 * minute) + 16;
                        break;
                    case 4: time = (0 * minute) + 24;
                        break;
                    case 5: time = (0 * minute) + 38;
                        break;
                    case 6: time = (0 * minute) + 56;
                        break;
                    case 7: time = (1 * minute) + 0;
                        break;
                    case 8: time = (1 * minute) + 14;
                        break;
                    case 9: time = (1 * minute) + 27;
                        break;
                    case 10: time = (1 * minute) + 42;
                        break;
                    case 11: time = (1 * minute) + 54;
                        break;
                    case 12: time = (2 * minute) + 12;
                        break;
                    case 13: time = (2 * minute) + 19;
                        break;
                    case 14: time = (2 * minute) + 28;
                        break;
                    case 15: time = (2 * minute) + 36;
                        break;
                    case 16: time = (2 * minute) + 43;
                        break;
                    case 17: time = (3 * minute) + 2;
                        break;
                    case 18: time = (3 * minute) + 13;
                        break;
                    case 19: time = (3 * minute) + 26;
                        break;
                    case 20: time = (3 * minute) + 50;
                        break;
                    case 21: time = (4 * minute) + 2;
                        break;
                    case 22: time = (4 * minute) + 10;
                        break;
                    case 23: time = (4 * minute) + 23;
                        break;
                    case 24: time = (4 * minute) + 35;
                        break;
                    case 25: time = (4 * minute) + 46;
                        break;
                    case 26: time = (4 * minute) + 59;
                        break;
                    case 27: time = (5 * minute) + 6;
                        break;
                    case 28: time = (5 * minute) + 27;
                        break;
                    case 29: time = (5 * minute) + 44;
                        break;
                    case 30: time = (6 * minute) + 0;
                        break;
                    case 31: time = (6 * minute) + 12;
                        break;
                    case 32: time = (6 * minute) + 32;
                        break;
                    case 33: time = (6 * minute) + 43;
                        break;
                    case 34: time = (6 * minute) + 56;
                }

                break;
            case 23: bookOfJoshua.removeAll();
            stage.addActor(bookOfJoshua.getTable23());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 10;
                        break;
                    case 3: time = (0 * minute) + 21;
                        break;
                    case 4: time = (0 * minute) + 30;
                        break;
                    case 5: time = (0 * minute) + 44;
                        break;
                    case 6: time = (0 * minute) + 55;
                        break;
                    case 7: time = (1 * minute) + 6;
                        break;
                    case 8: time = (1 * minute) + 16;
                        break;
                    case 9: time = (1 * minute) + 22;
                        break;
                    case 10: time = (1 * minute) + 32;
                        break;
                    case 11: time = (1 * minute) + 39;
                        break;
                    case 12: time = (1 * minute) + 44;
                        break;
                    case 13: time = (1 * minute) + 53;
                        break;
                    case 14: time = (2 * minute) + 10;
                        break;
                    case 15: time = (2 * minute) + 27;
                        break;
                    case 16: time = (2 * minute) + 42;
                }

                break;
            case 24: bookOfJoshua.removeAll();
            stage.addActor(bookOfJoshua.getTable24());

                switch(verse){
                    case 1: time = (0 * minute) + 0;
                        break;
                    case 2: time = (0 * minute) + 13;
                        break;
                    case 3: time = (0 * minute) + 28;
                        break;
                    case 4: time = (0 * minute) + 37;
                        break;
                    case 5: time = (0 * minute) + 46;
                        break;
                    case 6: time = (0 * minute) + 55;
                        break;
                    case 7: time = (1 * minute) + 4;
                        break;
                    case 8: time = (1 * minute) + 18;
                        break;
                    case 9: time = (1 * minute) + 30;
                        break;
                    case 10: time = (1 * minute) + 40;
                        break;
                    case 11: time = (1 * minute) + 47;
                        break;
                    case 12: time = (2 * minute) + 4;
                        break;
                    case 13: time = (2 * minute) + 13;
                        break;
                    case 14: time = (2 * minute) + 25;
                        break;
                    case 15: time = (2 * minute) + 37;
                        break;
                    case 16: time = (2 * minute) + 54;
                        break;
                    case 17: time = (3 * minute) + 2;
                        break;
                    case 18: time = (3 * minute) + 21;
                        break;
                    case 19: time = (3 * minute) + 35;
                        break;
                    case 20: time = (3 * minute) + 46;
                        break;
                    case 21: time = (3 * minute) + 55;
                        break;
                    case 22: time = (4 * minute) + 0;
                        break;
                    case 23: time = (4 * minute) + 13;
                        break;
                    case 24: time = (4 * minute) + 21;
                        break;
                    case 25: time = (4 * minute) + 29;
                        break;
                    case 26: time = (4 * minute) + 35;
                        break;
                    case 27: time = (4 * minute) + 45;
                        break;
                    case 28: time = (5 * minute) + 1;
                        break;
                    case 29: time = (5 * minute) + 6;
                        break;
                    case 30: time = (5 * minute) + 12;
                        break;
                    case 31: time = (5 * minute) + 20;
                        break;
                    case 32: time = (5 * minute) + 29;
                        break;
                    case 33: time = (5 * minute) + 44;
                }

                break;


        }
    }

    public void render(){
        stage.draw();
    }
}
